source 'https://gitcafe.com/akuandev/Specs.git'
target 'Courtesy', :exclusive => true do
    inhibit_all_warnings!
    pod 'JVFloatingDrawer'
    pod 'ZXingObjC'
    pod 'Colours'
    pod 'LBXScan'
    pod 'PEPhotoCropEditor'
    pod 'RSKImageCropper'
    pod 'LGAlertView'
    pod 'JSONModel'
    pod 'JDStatusBarNotification'
    pod 'UMengMessage'
    pod 'NJKWebViewProgress'
    pod 'AFNetworking'
    pod 'FCFileManager'
    pod 'Toast'
    pod 'UMengSocial', '~> 5.0'
    pod 'MJRefresh'
    pod 'YYKit'
    pod 'CJStringValidator'
    pod 'FMDB'
    pod 'CNCityPickerView'
    pod 'FDFullscreenPopGesture'
    pod 'SwipeView'
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    pod 'AFSoundManager'
    pod 'QBImagePickerController'
end
