source 'https://gitcafe.com/akuandev/Specs.git'
target 'Courtesy', :exclusive => true do
    inhibit_all_warnings!
    pod 'JVFloatingDrawer'
    pod 'ZXingObjC'
    pod 'Colours'
    pod 'LBXScan'
    pod 'LGAlertView'
    pod 'JSONModel'
    pod 'JDStatusBarNotification'
    pod 'UMengMessage'
    pod 'NJKWebViewProgress'
    pod 'AFNetworking'
    pod 'FCFileManager'
    pod 'Toast'
    pod 'UMengSocial', '4.3'
    pod 'MJRefresh'
    pod 'YYKit'
    pod 'CJStringValidator'
    pod 'FMDB'
    pod 'QBImagePickerController'
end
